version: '3.4'

services:
  neo4jtemplate:
    image: neo4j:4.3-community
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data:rw
      - ./examples:/var/lib/neo4j/import/examples:rw
